// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpuNodeServer.proto

#include "GpuNodeServer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace GpuNodeServer {
class createFileInputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<createFileInput>
      _instance;
} _createFileInput_default_instance_;
class createFileOutputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<createFileOutput>
      _instance;
} _createFileOutput_default_instance_;
class kernelCallInputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<kernelCallInput>
      _instance;
} _kernelCallInput_default_instance_;
class kernelCallOutputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<kernelCallOutput>
      _instance;
} _kernelCallOutput_default_instance_;
}  // namespace GpuNodeServer
namespace protobuf_GpuNodeServer_2eproto {
static void InitDefaultscreateFileInput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::GpuNodeServer::_createFileInput_default_instance_;
    new (ptr) ::GpuNodeServer::createFileInput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GpuNodeServer::createFileInput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_createFileInput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultscreateFileInput}, {}};

static void InitDefaultscreateFileOutput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::GpuNodeServer::_createFileOutput_default_instance_;
    new (ptr) ::GpuNodeServer::createFileOutput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GpuNodeServer::createFileOutput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_createFileOutput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultscreateFileOutput}, {}};

static void InitDefaultskernelCallInput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::GpuNodeServer::_kernelCallInput_default_instance_;
    new (ptr) ::GpuNodeServer::kernelCallInput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GpuNodeServer::kernelCallInput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_kernelCallInput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultskernelCallInput}, {}};

static void InitDefaultskernelCallOutput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::GpuNodeServer::_kernelCallOutput_default_instance_;
    new (ptr) ::GpuNodeServer::kernelCallOutput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GpuNodeServer::kernelCallOutput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_kernelCallOutput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultskernelCallOutput}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_createFileInput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_createFileOutput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_kernelCallInput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_kernelCallOutput.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::createFileInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::createFileInput, fsize_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::createFileInput, fpath_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::createFileOutput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::createFileOutput, msg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallInput, fpath_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallInput, func_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallInput, param_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallOutput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallOutput, fpath_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GpuNodeServer::kernelCallOutput, fsize_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::GpuNodeServer::createFileInput)},
  { 7, -1, sizeof(::GpuNodeServer::createFileOutput)},
  { 13, -1, sizeof(::GpuNodeServer::kernelCallInput)},
  { 21, -1, sizeof(::GpuNodeServer::kernelCallOutput)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::GpuNodeServer::_createFileInput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::GpuNodeServer::_createFileOutput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::GpuNodeServer::_kernelCallInput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::GpuNodeServer::_kernelCallOutput_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "GpuNodeServer.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023GpuNodeServer.proto\022\rGpuNodeServer\"/\n\017"
      "createFileInput\022\r\n\005fsize\030\001 \001(\003\022\r\n\005fpath\030"
      "\002 \001(\t\"\037\n\020createFileOutput\022\013\n\003msg\030\001 \001(\t\"="
      "\n\017kernelCallInput\022\r\n\005fpath\030\001 \001(\t\022\014\n\004func"
      "\030\002 \001(\t\022\r\n\005param\030\003 \001(\003\"0\n\020kernelCallOutpu"
      "t\022\r\n\005fpath\030\001 \001(\t\022\r\n\005fsize\030\002 \001(\0032\247\001\n\007GpuN"
      "ode\022M\n\nCreateFile\022\036.GpuNodeServer.create"
      "FileInput\032\037.GpuNodeServer.createFileOutp"
      "ut\022M\n\nCallKernel\022\036.GpuNodeServer.kernelC"
      "allInput\032\037.GpuNodeServer.kernelCallOutpu"
      "tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 409);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GpuNodeServer.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_GpuNodeServer_2eproto
namespace GpuNodeServer {

// ===================================================================

void createFileInput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int createFileInput::kFsizeFieldNumber;
const int createFileInput::kFpathFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

createFileInput::createFileInput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GpuNodeServer_2eproto::scc_info_createFileInput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GpuNodeServer.createFileInput)
}
createFileInput::createFileInput(const createFileInput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fpath().size() > 0) {
    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  fsize_ = from.fsize_;
  // @@protoc_insertion_point(copy_constructor:GpuNodeServer.createFileInput)
}

void createFileInput::SharedCtor() {
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fsize_ = GOOGLE_LONGLONG(0);
}

createFileInput::~createFileInput() {
  // @@protoc_insertion_point(destructor:GpuNodeServer.createFileInput)
  SharedDtor();
}

void createFileInput::SharedDtor() {
  fpath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void createFileInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* createFileInput::descriptor() {
  ::protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const createFileInput& createFileInput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GpuNodeServer_2eproto::scc_info_createFileInput.base);
  return *internal_default_instance();
}


void createFileInput::Clear() {
// @@protoc_insertion_point(message_clear_start:GpuNodeServer.createFileInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fpath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fsize_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool createFileInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GpuNodeServer.createFileInput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 fsize = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &fsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fpath = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fpath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fpath().data(), static_cast<int>(this->fpath().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GpuNodeServer.createFileInput.fpath"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GpuNodeServer.createFileInput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GpuNodeServer.createFileInput)
  return false;
#undef DO_
}

void createFileInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GpuNodeServer.createFileInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 fsize = 1;
  if (this->fsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->fsize(), output);
  }

  // string fpath = 2;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.createFileInput.fpath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->fpath(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GpuNodeServer.createFileInput)
}

::google::protobuf::uint8* createFileInput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GpuNodeServer.createFileInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 fsize = 1;
  if (this->fsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->fsize(), target);
  }

  // string fpath = 2;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.createFileInput.fpath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->fpath(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GpuNodeServer.createFileInput)
  return target;
}

size_t createFileInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GpuNodeServer.createFileInput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string fpath = 2;
  if (this->fpath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fpath());
  }

  // int64 fsize = 1;
  if (this->fsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->fsize());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void createFileInput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GpuNodeServer.createFileInput)
  GOOGLE_DCHECK_NE(&from, this);
  const createFileInput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const createFileInput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GpuNodeServer.createFileInput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GpuNodeServer.createFileInput)
    MergeFrom(*source);
  }
}

void createFileInput::MergeFrom(const createFileInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GpuNodeServer.createFileInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fpath().size() > 0) {

    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  if (from.fsize() != 0) {
    set_fsize(from.fsize());
  }
}

void createFileInput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GpuNodeServer.createFileInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void createFileInput::CopyFrom(const createFileInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GpuNodeServer.createFileInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool createFileInput::IsInitialized() const {
  return true;
}

void createFileInput::Swap(createFileInput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void createFileInput::InternalSwap(createFileInput* other) {
  using std::swap;
  fpath_.Swap(&other->fpath_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(fsize_, other->fsize_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata createFileInput::GetMetadata() const {
  protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void createFileOutput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int createFileOutput::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

createFileOutput::createFileOutput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GpuNodeServer_2eproto::scc_info_createFileOutput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GpuNodeServer.createFileOutput)
}
createFileOutput::createFileOutput(const createFileOutput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  // @@protoc_insertion_point(copy_constructor:GpuNodeServer.createFileOutput)
}

void createFileOutput::SharedCtor() {
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

createFileOutput::~createFileOutput() {
  // @@protoc_insertion_point(destructor:GpuNodeServer.createFileOutput)
  SharedDtor();
}

void createFileOutput::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void createFileOutput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* createFileOutput::descriptor() {
  ::protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const createFileOutput& createFileOutput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GpuNodeServer_2eproto::scc_info_createFileOutput.base);
  return *internal_default_instance();
}


void createFileOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:GpuNodeServer.createFileOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool createFileOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GpuNodeServer.createFileOutput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string msg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), static_cast<int>(this->msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GpuNodeServer.createFileOutput.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GpuNodeServer.createFileOutput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GpuNodeServer.createFileOutput)
  return false;
#undef DO_
}

void createFileOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GpuNodeServer.createFileOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string msg = 1;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.createFileOutput.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->msg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GpuNodeServer.createFileOutput)
}

::google::protobuf::uint8* createFileOutput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GpuNodeServer.createFileOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string msg = 1;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.createFileOutput.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GpuNodeServer.createFileOutput)
  return target;
}

size_t createFileOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GpuNodeServer.createFileOutput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string msg = 1;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void createFileOutput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GpuNodeServer.createFileOutput)
  GOOGLE_DCHECK_NE(&from, this);
  const createFileOutput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const createFileOutput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GpuNodeServer.createFileOutput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GpuNodeServer.createFileOutput)
    MergeFrom(*source);
  }
}

void createFileOutput::MergeFrom(const createFileOutput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GpuNodeServer.createFileOutput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
}

void createFileOutput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GpuNodeServer.createFileOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void createFileOutput::CopyFrom(const createFileOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GpuNodeServer.createFileOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool createFileOutput::IsInitialized() const {
  return true;
}

void createFileOutput::Swap(createFileOutput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void createFileOutput::InternalSwap(createFileOutput* other) {
  using std::swap;
  msg_.Swap(&other->msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata createFileOutput::GetMetadata() const {
  protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void kernelCallInput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int kernelCallInput::kFpathFieldNumber;
const int kernelCallInput::kFuncFieldNumber;
const int kernelCallInput::kParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

kernelCallInput::kernelCallInput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GpuNodeServer_2eproto::scc_info_kernelCallInput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GpuNodeServer.kernelCallInput)
}
kernelCallInput::kernelCallInput(const kernelCallInput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fpath().size() > 0) {
    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  func_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.func().size() > 0) {
    func_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.func_);
  }
  param_ = from.param_;
  // @@protoc_insertion_point(copy_constructor:GpuNodeServer.kernelCallInput)
}

void kernelCallInput::SharedCtor() {
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  func_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  param_ = GOOGLE_LONGLONG(0);
}

kernelCallInput::~kernelCallInput() {
  // @@protoc_insertion_point(destructor:GpuNodeServer.kernelCallInput)
  SharedDtor();
}

void kernelCallInput::SharedDtor() {
  fpath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  func_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void kernelCallInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* kernelCallInput::descriptor() {
  ::protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const kernelCallInput& kernelCallInput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GpuNodeServer_2eproto::scc_info_kernelCallInput.base);
  return *internal_default_instance();
}


void kernelCallInput::Clear() {
// @@protoc_insertion_point(message_clear_start:GpuNodeServer.kernelCallInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fpath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  func_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  param_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool kernelCallInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GpuNodeServer.kernelCallInput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string fpath = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fpath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fpath().data(), static_cast<int>(this->fpath().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GpuNodeServer.kernelCallInput.fpath"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string func = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_func()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->func().data(), static_cast<int>(this->func().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GpuNodeServer.kernelCallInput.func"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 param = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &param_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GpuNodeServer.kernelCallInput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GpuNodeServer.kernelCallInput)
  return false;
#undef DO_
}

void kernelCallInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GpuNodeServer.kernelCallInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string fpath = 1;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallInput.fpath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->fpath(), output);
  }

  // string func = 2;
  if (this->func().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->func().data(), static_cast<int>(this->func().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallInput.func");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->func(), output);
  }

  // int64 param = 3;
  if (this->param() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->param(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GpuNodeServer.kernelCallInput)
}

::google::protobuf::uint8* kernelCallInput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GpuNodeServer.kernelCallInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string fpath = 1;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallInput.fpath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->fpath(), target);
  }

  // string func = 2;
  if (this->func().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->func().data(), static_cast<int>(this->func().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallInput.func");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->func(), target);
  }

  // int64 param = 3;
  if (this->param() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->param(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GpuNodeServer.kernelCallInput)
  return target;
}

size_t kernelCallInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GpuNodeServer.kernelCallInput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string fpath = 1;
  if (this->fpath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fpath());
  }

  // string func = 2;
  if (this->func().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->func());
  }

  // int64 param = 3;
  if (this->param() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->param());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void kernelCallInput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GpuNodeServer.kernelCallInput)
  GOOGLE_DCHECK_NE(&from, this);
  const kernelCallInput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const kernelCallInput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GpuNodeServer.kernelCallInput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GpuNodeServer.kernelCallInput)
    MergeFrom(*source);
  }
}

void kernelCallInput::MergeFrom(const kernelCallInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GpuNodeServer.kernelCallInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fpath().size() > 0) {

    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  if (from.func().size() > 0) {

    func_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.func_);
  }
  if (from.param() != 0) {
    set_param(from.param());
  }
}

void kernelCallInput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GpuNodeServer.kernelCallInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void kernelCallInput::CopyFrom(const kernelCallInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GpuNodeServer.kernelCallInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool kernelCallInput::IsInitialized() const {
  return true;
}

void kernelCallInput::Swap(kernelCallInput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void kernelCallInput::InternalSwap(kernelCallInput* other) {
  using std::swap;
  fpath_.Swap(&other->fpath_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  func_.Swap(&other->func_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(param_, other->param_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata kernelCallInput::GetMetadata() const {
  protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void kernelCallOutput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int kernelCallOutput::kFpathFieldNumber;
const int kernelCallOutput::kFsizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

kernelCallOutput::kernelCallOutput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_GpuNodeServer_2eproto::scc_info_kernelCallOutput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GpuNodeServer.kernelCallOutput)
}
kernelCallOutput::kernelCallOutput(const kernelCallOutput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fpath().size() > 0) {
    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  fsize_ = from.fsize_;
  // @@protoc_insertion_point(copy_constructor:GpuNodeServer.kernelCallOutput)
}

void kernelCallOutput::SharedCtor() {
  fpath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fsize_ = GOOGLE_LONGLONG(0);
}

kernelCallOutput::~kernelCallOutput() {
  // @@protoc_insertion_point(destructor:GpuNodeServer.kernelCallOutput)
  SharedDtor();
}

void kernelCallOutput::SharedDtor() {
  fpath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void kernelCallOutput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* kernelCallOutput::descriptor() {
  ::protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const kernelCallOutput& kernelCallOutput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_GpuNodeServer_2eproto::scc_info_kernelCallOutput.base);
  return *internal_default_instance();
}


void kernelCallOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:GpuNodeServer.kernelCallOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fpath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fsize_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool kernelCallOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GpuNodeServer.kernelCallOutput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string fpath = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fpath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fpath().data(), static_cast<int>(this->fpath().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GpuNodeServer.kernelCallOutput.fpath"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 fsize = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &fsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GpuNodeServer.kernelCallOutput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GpuNodeServer.kernelCallOutput)
  return false;
#undef DO_
}

void kernelCallOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GpuNodeServer.kernelCallOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string fpath = 1;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallOutput.fpath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->fpath(), output);
  }

  // int64 fsize = 2;
  if (this->fsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->fsize(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GpuNodeServer.kernelCallOutput)
}

::google::protobuf::uint8* kernelCallOutput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GpuNodeServer.kernelCallOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string fpath = 1;
  if (this->fpath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fpath().data(), static_cast<int>(this->fpath().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GpuNodeServer.kernelCallOutput.fpath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->fpath(), target);
  }

  // int64 fsize = 2;
  if (this->fsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->fsize(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GpuNodeServer.kernelCallOutput)
  return target;
}

size_t kernelCallOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GpuNodeServer.kernelCallOutput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string fpath = 1;
  if (this->fpath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fpath());
  }

  // int64 fsize = 2;
  if (this->fsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->fsize());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void kernelCallOutput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GpuNodeServer.kernelCallOutput)
  GOOGLE_DCHECK_NE(&from, this);
  const kernelCallOutput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const kernelCallOutput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GpuNodeServer.kernelCallOutput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GpuNodeServer.kernelCallOutput)
    MergeFrom(*source);
  }
}

void kernelCallOutput::MergeFrom(const kernelCallOutput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GpuNodeServer.kernelCallOutput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fpath().size() > 0) {

    fpath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fpath_);
  }
  if (from.fsize() != 0) {
    set_fsize(from.fsize());
  }
}

void kernelCallOutput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GpuNodeServer.kernelCallOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void kernelCallOutput::CopyFrom(const kernelCallOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GpuNodeServer.kernelCallOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool kernelCallOutput::IsInitialized() const {
  return true;
}

void kernelCallOutput::Swap(kernelCallOutput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void kernelCallOutput::InternalSwap(kernelCallOutput* other) {
  using std::swap;
  fpath_.Swap(&other->fpath_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(fsize_, other->fsize_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata kernelCallOutput::GetMetadata() const {
  protobuf_GpuNodeServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GpuNodeServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GpuNodeServer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GpuNodeServer::createFileInput* Arena::CreateMaybeMessage< ::GpuNodeServer::createFileInput >(Arena* arena) {
  return Arena::CreateInternal< ::GpuNodeServer::createFileInput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GpuNodeServer::createFileOutput* Arena::CreateMaybeMessage< ::GpuNodeServer::createFileOutput >(Arena* arena) {
  return Arena::CreateInternal< ::GpuNodeServer::createFileOutput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GpuNodeServer::kernelCallInput* Arena::CreateMaybeMessage< ::GpuNodeServer::kernelCallInput >(Arena* arena) {
  return Arena::CreateInternal< ::GpuNodeServer::kernelCallInput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GpuNodeServer::kernelCallOutput* Arena::CreateMaybeMessage< ::GpuNodeServer::kernelCallOutput >(Arena* arena) {
  return Arena::CreateInternal< ::GpuNodeServer::kernelCallOutput >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
